version: "2.1"

networks:
    core-network:
        driver: bridge

services:
  userapi:
    container_name: userapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - core-network
    ports:
      - '5000:80'
