version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    container_name: "dev_user_mongo_container"
    environment:
      MONGO_INITDB_ROOT_USERNAME: abc
      MONGO_INITDB_ROOT_PASSWORD: abc
    ports:
      - 27017:27017
    volumes:
      - mongodb_user:/data/db

volumes:
  mongodb_user:
